/** Complete known service envelopes. Never match only a sender or a prefix:
 * any additional human request must continue through normal qualification. */
const VERTICER_FAQ = "Geachte relatie, Bedankt voor uw e-mail, wij streven ernaar deze zo spoedig mogelijk te beantwoorden. Hieronder treft u een aantal van onze 'Veelgestelde vragen [https://verticer.eu/nl/veelgestelde-vragen/]', waarmee u wellicht al geholpen bent. Algemeen * Hoe werkt MyVertiCer? De handleidingen kunt u vinden bij Downloads [https://verticer.eu/nl/downloads/]. * Hoe kom ik aan eHerkenning EH2+? Alle informatie over eHerkenning kunt u vinden op de website van eHerkenning [https://www.eherkenning.nl/nl]. Account of Productie-installatie aanmelden * Wilt u uw account en/of productie-installatie aanmelden? Dit kunt u doen via onze website [http://www.verticer.eu/]. U selecteert onder het kopje ‘Zelf regelen’ of uw een registratie doet als ‘Particulier’ of als ‘Producent’ (zakelijk). Vervolgens kiest u in het blok ‘Acties in MyVertiCer’ voor de optie ‘Ik wil mijzelf en/of mijn productie-installatie (opnieuw) aanmelden’. Let op: bij de registratie van een thermische-, groen gas of waterstof installatie is een meetprotocol nodig. Neem hiervoor contact op met uw meetbedrijf. Een wijziging doorvoeren * Wilt u een wijziging doorgeven? Bijvoorbeeld een handelaarswijziging, een verhuizing, een wijziging in relatie- of installatiegegevens? Klik hier [https://verticer.eu/nl/veelgestelde-vragen/een-wijziging-doorvoeren/] voor de benodigde stappen. Subsidie * Heeft u vragen over uw subsidie? Deze kunt u stellen aan RVO [https://rvo.nl/over-ons/contact]. * Heeft u vragen met betrekking tot Emissiereductie Eenheden (ERE)? Deze kunt u stellen aan Nea [https://emissieautoriteit.nl/]. Meetwaarden & rapportages * Wilt u zelf de meetwaarden van uw ingeschreven productie-installatie inzien, kies op onze website [http://www.verticer.eu/] ‘Voor particulieren’ of ‘Voor zakelijk’ en indien zakelijk, selecteert u vervolgens uw rol. Vervolgens scrolt u naar beneden naar ‘Acties in MyVertiCer’. * Zijn volgens u de meetwaarden elektriciteit niet juist of onvolledig, neem dan contact op met uw netbeheerder. * Heeft u een installatie voor thermische energie, groen gas of waterstof, dan kunt u voor vragen over de meetwaarden contact opnemen met uw meetbedrijf. * Heeft u een meet- en/of assurancerapport ingediend, dan nemen wij deze in behandeling. Bij vragen hierover nemen wij binnen acht weken contact met u op. LET OP! U kunt NIET op deze e-mail reageren.";
// Footer field shapes, not copied account numbers/contact records. Unknown
// prose anywhere in this suffix (including a P.S.) invalidates the template.
const VERTICER_FOOTER = /^Met vriendelijke groet, Servicedesk Verticer B\.V\. Postbus \d{1,6} \d{4} [A-Z]{2} [A-Z ]{2,60} servicedesk@verticer\.eu \[servicedesk@verticer\.eu\] www\.verticer\.eu \[https:\/\/verticer\.eu\/\] Handelsregister: [\p{L} -]{2,60} \d{6,12} IBAN: [A-Z]{2}\d{2}[A-Z\d]{10,30} Swift: BIC [A-Z\d]{8,11} VertiCer Logo\.png \* Denk aan het milieu\. Print dit bericht alleen als het noodzakelijk is\.$/u;

export function isCompleteServiceReceipt(sender: string, body: string): boolean {
  const compact = body.replace(/\[data:image\/[^\]]+\]/g, '').replace(/\s+/g, ' ').trim();
  if (sender === 'noreply@verticer.eu' && compact.startsWith(VERTICER_FAQ + ' ') &&
    VERTICER_FOOTER.test(compact.slice(VERTICER_FAQ.length).trim())) return true;
  // Zendesk's Dutch initial receipt. Later human ticket updates have a different
  // body and must not be mistaken for this acknowledgement.
  if (/^[^@]+@[^@]+\.zendesk\.com$/iu.test(sender) &&
    /^##- Typ uw reactie boven deze regel -## Geachte heer \/ mevrouw, Uw aanvraag met ticket nummer \(\d{1,12}\) is door ons in goede orde ontvangen en wordt door een van onze helpdesk medewerkers in behandeling genomen\. Als u aanvullende opmerkingen wilt toevoegen, reageer dan op dit e-mailbericht\. -{10,} Dit e-mailbericht is een service van [\p{L}\p{N} &-]{2,80}\. \[[A-Z0-9]{6}-[A-Z0-9]{5}\]$/u.test(compact)) return true;
  const dental = /^Благодарим Вас за обращение в стоматологию [\p{L}«»" -]{2,60}\. В ближайшее время наш администратор свяжется с вами\.\s+Наш адрес{1,2}: [^\n]{5,100}\nтел\. [\d ()+-]{7,30} viber \+\d{10,15} Whatsapp \+\d{10,15}\s*$/iu;
  if (dental.test(body.trim())) return true;
  const processing = /^Добрый день!\s+Благодарим за обращение в ООО "[^"\n]{2,60}"\.\s+Ваш запрос находится в обработке, наши менеджеры свяжутся с Вами в ближайшее время\.\s+Внимание! Если с Вами до конца рабочего дня не связался наш менеджер, сообщите нам удобным для Вас способом:\s+Тел\. \+?[\d ()-]{7,30}\s+\+?[\d ()-]{7,30} доб\.\d{1,6}(?:, \d{1,6}){0,5}\s+Эл\. Почта [^\s@,]+@[^\s@,]+(?:, [^\s@,]+@[^\s@,]+)*\.\s+С уважением,\s+отдел сервиса клиентов\.\s*$/iu;
  return processing.test(body.trim());
}
