#!/bin/sh
# ──────────────────────────────────────────────────────────────────────────────
# Entrypoint для контейнера portal-backup.
#
# Зачем нужен: BusyBox crond передаёт ребёнку только HOME/PATH/LOGNAME/SHELL,
# плюс свой собственный environ на момент старта. Если контейнер был перезапущен
# через `docker restart` (а не пересоздан), crond сохраняет старый env, и
# /backup.sh может уйти в S3 со старыми кредами/регионом/бакетом.
#
# Решение: при каждом старте контейнера снапшотим текущий env в /etc/backup.env,
# а cron-job в /etc/crontabs/root делает `. /etc/backup.env` перед /backup.sh.
# Так гарантируем, что cron-job всегда видит актуальные BACKUP_S3_* /
# MAIN_S3_* / TELEGRAM_HEALTH_* / *_DATABASE_URL — даже после рестарта.
# ──────────────────────────────────────────────────────────────────────────────

set -eu

ENV_FILE=/etc/backup.env

# Сохраняем env как `export KEY='value'` через awk: одинарные кавычки в значении
# заменяем на `'\''` (стандартный POSIX-приём). awk читает env через ENVIRON,
# поэтому ничего не парсит из stdout `env` — это устойчиво к значениям с `=` и
# другими спецсимволами внутри.
#
# Реализация awk-программы лежит в отдельном файле (/usr/local/bin/dump_env.awk),
# чтобы не воевать с цитированием одинарных кавычек внутри shell-heredoc.
{
  printf '# Generated by /entrypoint.sh at %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  awk -f /usr/local/bin/dump_env.awk < /dev/null
} > "$ENV_FILE"
chmod 600 "$ENV_FILE"

echo "[entrypoint] env snapshot written to ${ENV_FILE} ($(wc -l < "$ENV_FILE") lines)"
echo "[entrypoint] starting crond..."

# crond в фоне; tail на лог чтобы контейнер не завершался и логи шли в stdout.
crond -f -l 2 &
CRON_PID=$!

tail -f /var/log/cron.log &
TAIL_PID=$!

backup_job_active() {
  # Шаблон с [] не совпадает с собственной командой grep.
  ps -o args 2>/dev/null | grep -q '[/]backup[.]sh '
}

graceful_shutdown() {
  # Compose может пересоздать контейнер ровно между внешней проверкой процессов
  # и `docker compose up`. Ставим crond на паузу, чтобы он не запустил новую
  # задачу, и держим PID 1 живым до завершения текущего dump + S3 upload.
  trap - INT TERM
  echo "[entrypoint] shutdown requested; draining active backup job..."
  kill -STOP "$CRON_PID" 2>/dev/null || true
  while backup_job_active; do
    sleep 5
  done
  kill -CONT "$CRON_PID" 2>/dev/null || true
  kill -TERM "$CRON_PID" 2>/dev/null || true
  wait "$CRON_PID" 2>/dev/null || true
  kill -TERM "$TAIL_PID" 2>/dev/null || true
  wait "$TAIL_PID" 2>/dev/null || true
  echo "[entrypoint] graceful shutdown complete"
  exit 0
}

trap graceful_shutdown INT TERM

wait "$CRON_PID"
kill -TERM "$TAIL_PID" 2>/dev/null || true
