# Generated by Django 6.0.3 on 2026-03-17 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("product_docs", models.TextField(blank=True)),
                ("campaign_objective", models.TextField(blank=True)),
                ("booking_link", models.URLField(blank=True, max_length=500)),
                ("is_freemium", models.BooleanField(default=False)),
                ("action_fraction", models.FloatField(default=0.2)),
                ("seed_public_ids", models.JSONField(blank=True, default=list)),
                ("model_blob", models.BinaryField(blank=True, null=True)),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LinkedInProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("linkedin_username", models.CharField(max_length=200)),
                ("linkedin_password", models.CharField(max_length=200)),
                ("subscribe_newsletter", models.BooleanField(default=True)),
                ("active", models.BooleanField(default=True)),
                ("connect_daily_limit", models.PositiveIntegerField(default=20)),
                ("connect_weekly_limit", models.PositiveIntegerField(default=100)),
                ("follow_up_daily_limit", models.PositiveIntegerField(default=30)),
                ("legal_accepted", models.BooleanField(default=False)),
                ("cookie_data", models.JSONField(blank=True, null=True)),
                ("newsletter_processed", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linkedin_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("connect", "Connect"),
                            ("check_pending", "Check Pending"),
                            ("follow_up", "Follow Up"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                ("payload", models.JSONField(default=dict)),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "scheduled_at"],
                        name="linkedin_ta_status_d04eec_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[("connect", "Connect"), ("follow_up", "Follow Up")],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_logs",
                        to="linkedin.campaign",
                    ),
                ),
                (
                    "linkedin_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_logs",
                        to="linkedin.linkedinprofile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["linkedin_profile", "action_type", "created_at"],
                        name="linkedin_ac_linkedi_37318d_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SearchKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=500)),
                ("used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_keywords",
                        to="linkedin.campaign",
                    ),
                ),
            ],
            options={
                "unique_together": {("campaign", "keyword")},
            },
        ),
    ]
