# Generated by Django 6.0.3 on 2026-04-11 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0004_compress_campaign_model_blob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='error',
        ),
    ]
