# Generated by Django 6.0.3 on 2026-04-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("linkedin", "0005_remove_task_error"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linkedinprofile",
            name="follow_up_daily_limit",
            field=models.PositiveIntegerField(default=25),
        ),
    ]
