-- Company-wide payment request control.
-- Browser roles can use only the guarded RPCs below; the base rows and audit
-- trail stay service-owned. All monthly accounting uses Europe/Moscow dates.

create table if not exists public.payment_request_managers (
  user_id uuid primary key
    references public.profiles(id) on delete cascade,
  granted_at timestamptz not null default now(),
  granted_by uuid
    references public.profiles(id) on delete set null
);

insert into public.payment_request_managers (user_id)
select id
from public.profiles
where id = '9e2c53fe-4b86-40b1-b464-757ffe0944dd'::uuid
on conflict (user_id) do nothing;

create table if not exists public.payment_request_events (
  id bigint generated by default as identity primary key,
  payment_request_id uuid not null
    references public.payment_requests(id) on delete restrict,
  actor_user_id uuid
    references public.profiles(id) on delete set null,
  actor_name text not null,
  event_type text not null,
  from_status text,
  to_status text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.payment_requests
  add column if not exists expense_type text,
  add column if not exists expected_payment_on date,
  add column if not exists urgency text not null default 'normal',
  add column if not exists document_url text,
  add column if not exists approval_reason text,
  add column if not exists paid_on date,
  add column if not exists paid_on_source text,
  add column if not exists paid_by uuid,
  add column if not exists paid_at timestamptz,
  add column if not exists requester_user_id uuid,
  add column if not exists requester_name text,
  add column if not exists idempotency_key uuid,
  add column if not exists submission_fingerprint text,
  add column if not exists updated_at timestamptz not null default now();

alter table public.payment_requests
  drop constraint if exists payment_requests_paid_by_fkey;
alter table public.payment_requests
  add constraint payment_requests_paid_by_fkey
  foreign key (paid_by) references public.profiles(id) on delete set null;

-- The legacy CHECK does not include `paid`; remove it before changing old rows.
alter table public.payment_requests
  drop constraint if exists payment_requests_status_check;

-- Existing rows never had a type or trustworthy payment date. Keep them in
-- the current-month totals conservatively until the manager classifies them.
update public.payment_requests set expense_type = 'legacy_unclassified', status = 'paid', expected_payment_on = (created_at at time zone 'Europe/Moscow')::date, paid_on = (created_at at time zone 'Europe/Moscow')::date, paid_on_source = 'legacy_created_at', paid_by = null, updated_at = coalesce(updated_at, created_at) where expense_type is null;

insert into public.payment_request_events (
  payment_request_id,
  actor_user_id,
  actor_name,
  event_type,
  from_status,
  to_status,
  metadata,
  created_at
)
select request.id,
       null,
       'Система',
       'legacy_backfilled',
       null,
       'paid',
       jsonb_build_object(
         'expense_type', 'legacy_unclassified',
         'paid_on_source', 'legacy_created_at',
         'approximated_from', 'created_at'
       ),
       now()
from public.payment_requests request
where request.expense_type = 'legacy_unclassified'
  and not exists (
    select 1
    from public.payment_request_events event
    where event.payment_request_id = request.id
      and event.event_type = 'legacy_backfilled'
  );

-- Freeze who asked for the money. The live profile link may later be cleared
-- by an offboarding, but the request and its audit trail must stay readable.
update public.payment_requests request
   set requester_user_id = request.user_id,
       requester_name = coalesce(nullif(btrim(requester.full_name), ''), 'Неизвестно')
  from public.profiles requester
 where requester.id = request.user_id
   and (request.requester_user_id is null or request.requester_name is null);

update public.payment_requests
   set requester_user_id = coalesce(requester_user_id, user_id),
       requester_name = coalesce(requester_name, 'Неизвестно')
 where requester_user_id is null
    or requester_name is null;

alter table public.payment_requests
  alter column expense_type set not null,
  alter column expected_payment_on set not null,
  alter column updated_at set not null,
  alter column requester_user_id set not null,
  alter column requester_name set not null;

-- Hard-deleting an employee must not erase financial history: the live link is
-- cleared, the frozen requester snapshot and the append-only audit stay.
alter table public.payment_requests
  drop constraint if exists payment_requests_user_id_fkey;
alter table public.payment_requests
  alter column user_id drop not null;
alter table public.payment_requests
  add constraint payment_requests_user_id_fkey
  foreign key (user_id) references public.profiles(id) on delete set null;

alter table public.payment_requests
  drop constraint if exists payment_requests_expense_type_check,
  drop constraint if exists payment_requests_urgency_check,
  drop constraint if exists payment_requests_approval_reason_check,
  drop constraint if exists payment_requests_paid_on_source_check,
  drop constraint if exists payment_requests_document_url_length_check,
  drop constraint if exists payment_requests_document_url_scheme_check,
  drop constraint if exists payment_requests_paid_lifecycle_check,
  drop constraint if exists payment_requests_idempotency_pairing_check,
  drop constraint if exists payment_requests_submission_fingerprint_check;

alter table public.payment_requests
  add constraint payment_requests_status_check
    check (status in ('pending', 'approved', 'paid', 'rejected')),
  add constraint payment_requests_expense_type_check
    check (expense_type in ('one_time', 'planned', 'legacy_unclassified')),
  add constraint payment_requests_urgency_check
    check (urgency in ('normal', 'urgent', 'critical')),
  add constraint payment_requests_approval_reason_check
    check (approval_reason is null or approval_reason in ('planned', 'limit_exceeded')),
  add constraint payment_requests_paid_on_source_check
    check (paid_on_source is null or paid_on_source in ('entered', 'legacy_created_at')),
  add constraint payment_requests_document_url_length_check
    check (document_url is null or char_length(document_url) <= 2000),
  add constraint payment_requests_document_url_scheme_check
    check (document_url is null or document_url ~* '^https?://'),
  add constraint payment_requests_paid_lifecycle_check
    check (
      (status = 'paid' and paid_on is not null and paid_on_source is not null)
      or (status <> 'paid' and paid_on is null and paid_on_source is null)
    ),
  add constraint payment_requests_idempotency_pairing_check
    check ((idempotency_key is null) = (submission_fingerprint is null)),
  add constraint payment_requests_submission_fingerprint_check
    check (submission_fingerprint is null or char_length(submission_fingerprint) = 64);

-- One stored submission per (author, key): a lost response replays this row
-- instead of reserving the monthly limit a second time.
create unique index if not exists uq_payment_requests_idempotency
  on public.payment_requests (requester_user_id, idempotency_key)
  where idempotency_key is not null;

create index if not exists idx_payment_requests_expected_payment_on
  on public.payment_requests(expected_payment_on, status);
create index if not exists idx_payment_requests_paid_on
  on public.payment_requests(paid_on)
  where status = 'paid';

drop trigger if exists trg_payment_requests_updated_at
  on public.payment_requests;
create trigger trg_payment_requests_updated_at
  before update on public.payment_requests
  for each row
  execute function public.set_updated_at();

create or replace function public.can_use_payment_requests()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles actor
    where actor.id = auth.uid()
      and coalesce(actor.is_demo, false) = false
      and actor.role in ('technician', 'manager', 'director', 'admin', 'sales', 'marketer', 'lead')
  );
$$;

create or replace function public.can_manage_payment_requests()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.payment_request_managers manager
    join public.profiles actor
      on actor.id = manager.user_id
    where actor.id = auth.uid()
      and coalesce(actor.is_demo, false) = false
      and actor.role in ('technician', 'manager', 'director', 'admin', 'sales', 'marketer', 'lead')
  );
$$;

create or replace function public.payment_request_month_limit(p_month date)
returns numeric
language sql
immutable
set search_path = ''
as $$
  select case
    when extract(month from p_month) in (1, 5, 12) then 40000::numeric
    else 75000::numeric
  end;
$$;

create or replace function public.lock_payment_request_months(p_months date[])
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform pg_advisory_xact_lock(
    hashtextextended('payment_requests:' || locked.month_start::text, 0)
  )
  from (
    select distinct date_trunc('month', month_value)::date as month_start
    from unnest(p_months) as requested(month_value)
    where month_value is not null
    order by month_start
  ) locked;
end;
$$;

create or replace function public.lock_payment_request_submission(
  p_actor_id uuid,
  p_idempotency_key uuid
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform pg_advisory_xact_lock(
    hashtextextended(
      'payment_request_submission_idempotency:'
        || p_actor_id::text || ':' || p_idempotency_key::text,
      0
    )
  );
end;
$$;

create or replace function public.payment_request_month_summary(p_month date)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_month date := date_trunc('month', p_month)::date;
  v_next date := (date_trunc('month', p_month) + interval '1 month')::date;
  v_limit numeric := public.payment_request_month_limit(p_month);
  v_paid_one_time numeric := 0;
  v_reserved_one_time numeric := 0;
  v_paid_all numeric := 0;
  v_legacy_count bigint := 0;
  v_legacy_amount numeric := 0;
  v_pending_count bigint := 0;
  v_approved_count bigint := 0;
  v_used numeric;
  v_remaining numeric;
  v_usage_pct numeric;
begin
  if not public.can_use_payment_requests() then
    raise exception 'payment_request_forbidden' using errcode = '42501';
  end if;

  select coalesce(sum(request.amount) filter (
           where request.status = 'paid'
             and request.paid_on >= v_month
             and request.paid_on < v_next
             and request.expense_type in ('one_time', 'legacy_unclassified')
         ), 0),
         coalesce(sum(request.amount) filter (
           where request.status = 'approved'
             and request.expected_payment_on >= v_month
             and request.expected_payment_on < v_next
             and request.expense_type = 'one_time'
         ), 0),
         coalesce(sum(request.amount) filter (
           where request.status = 'paid'
             and request.paid_on >= v_month
             and request.paid_on < v_next
         ), 0),
         count(*) filter (
           where request.status = 'paid'
             and request.paid_on >= v_month
             and request.paid_on < v_next
             and request.expense_type = 'legacy_unclassified'
         ),
         coalesce(sum(request.amount) filter (
           where request.status = 'paid'
             and request.paid_on >= v_month
             and request.paid_on < v_next
             and request.expense_type = 'legacy_unclassified'
         ), 0)
  into v_paid_one_time,
       v_reserved_one_time,
       v_paid_all,
       v_legacy_count,
       v_legacy_amount
  from public.payment_requests request;

  select count(*) filter (
           where request.status = 'pending'
             and request.expected_payment_on >= v_month
             and request.expected_payment_on < v_next
         ),
         count(*) filter (
           where request.status = 'approved'
             and request.expected_payment_on >= v_month
             and request.expected_payment_on < v_next
         )
  into v_pending_count,
       v_approved_count
  from public.payment_requests request;

  v_used := v_paid_one_time + v_reserved_one_time;
  v_remaining := v_limit - v_used;
  v_usage_pct := case when v_limit = 0 then 0 else (v_used / v_limit) * 100 end;

  return jsonb_build_object(
    'limit', v_limit,
    'paidOneTime', v_paid_one_time,
    'reservedOneTime', v_reserved_one_time,
    'usedOneTime', v_used,
    'remaining', v_remaining,
    'overage', greatest(v_used - v_limit, 0),
    'usagePct', v_usage_pct,
    'level', case
      when v_usage_pct > 100 then 'exceeded'
      when v_usage_pct >= 80 then 'warning'
      else 'normal'
    end,
    'legacyCount', v_legacy_count,
    'legacyAmount', v_legacy_amount,
    'paidAll', v_paid_all,
    'pendingCount', v_pending_count,
    'approvedCount', v_approved_count
  );
end;
$$;

create or replace function public.payment_request_api_record(p_request_id uuid)
returns jsonb
language sql
volatile
security definer
set search_path = ''
as $$
  select jsonb_build_object(
           'id', request.id,
           'user_id', request.requester_user_id,
           'requester_name', request.requester_name,
           'department', request.department,
           'description', request.description,
           'amount', request.amount,
           'project_id', request.project_id,
           'project_name', project.name,
           'project_client', project.client,
           'comment', request.comment,
           'expense_type', request.expense_type,
           'status', request.status,
           'approval_reason', request.approval_reason,
           'expected_payment_on', request.expected_payment_on,
           'paid_on', request.paid_on,
           'paid_on_source', request.paid_on_source,
           'urgency', request.urgency,
           'decider_name', decider.full_name,
           'decided_by', request.decided_by,
           'decided_at', request.decided_at,
           'decision_comment', request.decision_comment,
           'paid_by', request.paid_by,
           'paid_by_name', payer.full_name,
           'paid_at', request.paid_at,
           'created_at', request.created_at,
           'updated_at', request.updated_at,
           'document_url', case
             when auth.uid() = request.user_id
               or public.can_manage_payment_requests()
             then request.document_url
             else null
           end
         )
  from public.payment_requests request
  left join public.projects project on project.id = request.project_id
  left join public.profiles decider on decider.id = request.decided_by
  left join public.profiles payer on payer.id = request.paid_by
  where request.id = p_request_id;
$$;

create or replace function public.list_payment_requests(p_month date)
returns table (
  id uuid,
  user_id uuid,
  requester_name text,
  department text,
  description text,
  amount numeric,
  project_id uuid,
  project_name text,
  project_client text,
  comment text,
  expense_type text,
  status text,
  approval_reason text,
  expected_payment_on date,
  paid_on date,
  paid_on_source text,
  urgency text,
  document_url text,
  decided_by uuid,
  decider_name text,
  decided_at timestamptz,
  decision_comment text,
  paid_by uuid,
  paid_by_name text,
  paid_at timestamptz,
  created_at timestamptz,
  updated_at timestamptz
)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_month date := date_trunc('month', p_month)::date;
  v_next date := (date_trunc('month', p_month) + interval '1 month')::date;
begin
  if not public.can_use_payment_requests() then
    raise exception 'payment_request_forbidden' using errcode = '42501';
  end if;

  return query
  select request.id,
         request.requester_user_id,
         request.requester_name,
         request.department,
         request.description,
         request.amount,
         request.project_id,
         project.name,
         project.client,
         request.comment,
         request.expense_type,
         request.status,
         request.approval_reason,
         request.expected_payment_on,
         request.paid_on,
         request.paid_on_source,
         request.urgency,
         case when auth.uid() = request.user_id or public.can_manage_payment_requests() then request.document_url else null end,
         request.decided_by,
         decider.full_name,
         request.decided_at,
         request.decision_comment,
         request.paid_by,
         payer.full_name,
         request.paid_at,
         request.created_at,
         request.updated_at
  from public.payment_requests request
  left join public.projects project on project.id = request.project_id
  left join public.profiles decider on decider.id = request.decided_by
  left join public.profiles payer on payer.id = request.paid_by
  where (
    request.expected_payment_on >= v_month
    and request.expected_payment_on < v_next
  ) or (
    request.paid_on >= v_month
    and request.paid_on < v_next
  )
  order by coalesce(request.paid_on, request.expected_payment_on) desc,
           request.created_at desc,
           request.id;
end;
$$;

-- The pre-idempotency signature must not survive as a callable overload.
drop function if exists public.submit_payment_request(text, text, numeric, uuid, text, text, date, text, text);

create or replace function public.submit_payment_request(
  p_idempotency_key uuid,
  p_department text,
  p_description text,
  p_amount numeric,
  p_project_id uuid,
  p_comment text,
  p_expense_type text,
  p_expected_payment_on date,
  p_urgency text,
  p_document_url text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor_id uuid := auth.uid();
  v_actor_name text;
  v_month date := date_trunc('month', p_expected_payment_on)::date;
  v_submission_fingerprint text;
  v_existing public.payment_requests%rowtype;
  v_summary jsonb;
  v_remaining numeric;
  v_status text;
  v_approval_reason text;
  v_outcome text;
  v_request_id uuid;
begin
  if v_actor_id is null or not public.can_use_payment_requests() then
    raise exception 'payment_request_forbidden' using errcode = '42501';
  end if;
  if p_idempotency_key is null
     or p_department is null
     or p_department not in ('outreach', 'paid_traffic', 'accounting', 'sales')
     or p_expense_type is null
     or not (p_expense_type in ('one_time', 'planned'))
     or p_urgency is null
     or p_urgency not in ('normal', 'urgent', 'critical')
     or p_expected_payment_on is null
     or p_amount is null
     or p_amount <= 0
     or p_amount > 9999999999.99
     or p_amount <> round(p_amount, 2)
     or char_length(btrim(coalesce(p_description, ''))) not between 1 and 500
     or (p_comment is not null and char_length(p_comment) > 5000)
     or (p_document_url is not null and (
       char_length(p_document_url) > 2000
       or p_document_url !~* '^https?://'
     ))
  then
    raise exception 'payment_request_invalid_input' using errcode = '22023';
  end if;
  if p_project_id is not null and not exists (
    select 1
    from public.projects project
    where project.id = p_project_id
  ) then
    raise exception 'payment_request_project_not_found' using errcode = 'P0002';
  end if;

  -- Freeze the author now: the audit trail must stay readable after offboarding.
  select coalesce(nullif(btrim(actor.full_name), ''), 'Неизвестно')
  into v_actor_name
  from public.profiles actor
  where actor.id = v_actor_id;
  v_actor_name := coalesce(v_actor_name, 'Неизвестно');

  -- Canonical payload hash. Same key with the same data replays the stored
  -- decision; same key with different data is a client bug, not a new reserve.
  v_submission_fingerprint := encode(
    sha256(convert_to(jsonb_build_object(
      'department', p_department,
      'description', btrim(p_description),
      'amount', round(p_amount, 2)::text,
      'project_id', p_project_id,
      'comment', nullif(btrim(p_comment), ''),
      'expense_type', p_expense_type,
      'expected_payment_on', p_expected_payment_on,
      'urgency', p_urgency,
      'document_url', nullif(btrim(p_document_url), '')
    )::text, 'utf8')),
    'hex'
  );

  perform public.lock_payment_request_submission(v_actor_id, p_idempotency_key);

  select request.*
  into v_existing
  from public.payment_requests request
  where request.requester_user_id = v_actor_id
    and request.idempotency_key = p_idempotency_key;

  if found then
    if v_existing.submission_fingerprint is distinct from v_submission_fingerprint then
      raise exception 'payment_request_idempotency_conflict' using errcode = '23505';
    end if;
    perform public.lock_payment_request_months(array[v_month]);
    return jsonb_build_object(
      'request', public.payment_request_api_record(v_existing.id),
      'summary', public.payment_request_month_summary(v_month),
      'outcome', case
        when v_existing.status = 'approved' then 'auto_approved'
        else 'approval_required'
      end
    );
  end if;

  perform public.lock_payment_request_months(array[v_month]);
  v_summary := public.payment_request_month_summary(v_month);
  v_remaining := (v_summary ->> 'remaining')::numeric;

  if p_expense_type = 'planned' then
    v_status := 'pending';
    v_approval_reason := 'planned';
    v_outcome := 'approval_required';
  elsif p_amount <= v_remaining then
    v_status := 'approved';
    v_approval_reason := null;
    v_outcome := 'auto_approved';
  else
    v_status := 'pending';
    v_approval_reason := 'limit_exceeded';
    v_outcome := 'approval_required';
  end if;

  insert into public.payment_requests (
    user_id,
    requester_user_id,
    requester_name,
    department,
    description,
    amount,
    project_id,
    comment,
    expense_type,
    expected_payment_on,
    urgency,
    document_url,
    status,
    approval_reason,
    decided_by,
    decided_at,
    decision_comment,
    idempotency_key,
    submission_fingerprint
  )
  values (
    v_actor_id,
    v_actor_id,
    v_actor_name,
    p_department,
    btrim(p_description),
    p_amount,
    p_project_id,
    nullif(btrim(p_comment), ''),
    p_expense_type,
    p_expected_payment_on,
    p_urgency,
    nullif(btrim(p_document_url), ''),
    v_status,
    v_approval_reason,
    null,
    null,
    null,
    p_idempotency_key,
    v_submission_fingerprint
  )
  returning id into v_request_id;

  insert into public.payment_request_events (
    payment_request_id,
    actor_user_id,
    actor_name,
    event_type,
    from_status,
    to_status,
    metadata
  ) values (
    v_request_id,
    v_actor_id,
    v_actor_name,
    case when v_outcome = 'auto_approved' then 'submitted_auto_approved' else 'submitted_for_approval' end,
    null,
    v_status,
    jsonb_build_object(
      'expense_type', p_expense_type,
      'expected_payment_on', p_expected_payment_on,
      'approval_reason', v_approval_reason
    )
  );

  v_summary := public.payment_request_month_summary(v_month);

  return jsonb_build_object(
    'request', public.payment_request_api_record(v_request_id),
    'summary', v_summary,
    'outcome', v_outcome
  );
end;
$$;

create or replace function public.transition_payment_request(
  p_request_id uuid,
  p_action text,
  p_expected_updated_at timestamptz,
  p_decision_comment text default null,
  p_paid_on date default null,
  p_expense_type text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor_id uuid := auth.uid();
  v_actor_name text;
  v_request public.payment_requests%rowtype;
  v_updated public.payment_requests%rowtype;
  v_lock_months date[];
  v_affected_months text[];
  v_month_key text;
  v_summaries jsonb := '[]'::jsonb;
  v_outcome text;
begin
  if v_actor_id is null or not public.can_manage_payment_requests() then
    raise exception 'payment_request_forbidden' using errcode = '42501';
  end if;
  if p_action is null or p_action not in ('approve', 'reject', 'mark_paid', 'classify_legacy') then
    raise exception 'payment_request_invalid_transition' using errcode = '23514';
  end if;
  if p_expected_updated_at is null then
    raise exception 'payment_request_conflict' using errcode = '40001';
  end if;

  -- Freeze the manager who decided, so the trail survives their offboarding.
  select coalesce(nullif(btrim(actor.full_name), ''), 'Неизвестно')
  into v_actor_name
  from public.profiles actor
  where actor.id = v_actor_id;
  v_actor_name := coalesce(v_actor_name, 'Неизвестно');

  select request.*
  into v_request
  from public.payment_requests request
  where request.id = p_request_id
  for update;

  if not found then
    raise exception 'payment_request_not_found' using errcode = 'P0002';
  end if;
  if v_request.updated_at is distinct from p_expected_updated_at then
    raise exception 'payment_request_conflict' using errcode = '40001';
  end if;

  if p_action = 'mark_paid' and v_request.status <> 'approved' then
    raise exception 'payment_request_invalid_transition' using errcode = '23514';
  end if;
  if p_action = 'classify_legacy' and p_paid_on is null then raise exception 'payment_request_invalid_transition' using errcode = '23514'; end if;
  if p_action = 'classify_legacy'
     and (
       v_request.expense_type <> 'legacy_unclassified'
       or v_request.status <> 'paid'
     )
  then
    raise exception 'payment_request_invalid_transition' using errcode = '23514';
  end if;
  if p_action = 'approve' and v_request.status <> 'pending' then
    raise exception 'payment_request_invalid_transition' using errcode = '23514';
  end if;
  if p_action = 'reject' and v_request.status not in ('pending', 'approved') then
    raise exception 'payment_request_invalid_transition' using errcode = '23514';
  end if;
  if p_action = 'reject'
     and char_length(btrim(coalesce(p_decision_comment, ''))) not between 1 and 1000
  then
    raise exception 'payment_request_invalid_transition' using errcode = '23514';
  end if;
  if p_action = 'approve'
     and p_decision_comment is not null
     and char_length(p_decision_comment) > 1000
  then
    raise exception 'payment_request_invalid_transition' using errcode = '23514';
  end if;
  if p_action in ('approve', 'reject')
     and (p_paid_on is not null or p_expense_type is not null)
  then
    raise exception 'payment_request_invalid_transition' using errcode = '23514';
  end if;
  if p_action = 'mark_paid'
     and (p_decision_comment is not null or p_expense_type is not null)
  then
    raise exception 'payment_request_invalid_transition' using errcode = '23514';
  end if;
  if p_action = 'classify_legacy' and p_decision_comment is not null then
    raise exception 'payment_request_invalid_transition' using errcode = '23514';
  end if;
  if p_action in ('mark_paid', 'classify_legacy')
     and (
       p_paid_on is null
       or p_paid_on > (now() at time zone 'Europe/Moscow')::date
     )
  then
    raise exception 'payment_request_invalid_transition' using errcode = '23514';
  end if;
  if p_action = 'classify_legacy'
     and (p_expense_type is null or p_expense_type not in ('one_time', 'planned'))
  then
    raise exception 'payment_request_invalid_transition' using errcode = '23514';
  end if;

  if p_action in ('approve', 'reject') then
    v_lock_months := array[date_trunc('month', v_request.expected_payment_on)::date];
  elsif p_action = 'mark_paid' then
    v_lock_months := array[
      date_trunc('month', v_request.expected_payment_on)::date,
      date_trunc('month', p_paid_on)::date
    ];
  else
    v_lock_months := array[
      date_trunc('month', v_request.paid_on)::date,
      date_trunc('month', p_paid_on)::date
    ];
  end if;
  perform public.lock_payment_request_months(v_lock_months);

  if p_action = 'approve' then
    update public.payment_requests
    set status = 'approved',
        decided_by = v_actor_id,
        decided_at = now(),
        decision_comment = nullif(btrim(p_decision_comment), ''),
        updated_at = now()
    where id = v_request.id
    returning * into v_updated;
    v_outcome := 'approved';
  elsif p_action = 'reject' then
    update public.payment_requests
    set status = 'rejected',
        decided_by = v_actor_id,
        decided_at = now(),
        decision_comment = btrim(p_decision_comment),
        updated_at = now()
    where id = v_request.id
    returning * into v_updated;
    v_outcome := 'rejected';
  elsif p_action = 'mark_paid' then
    update public.payment_requests
    set status = 'paid',
        paid_on = p_paid_on,
        paid_on_source = 'entered',
        paid_by = auth.uid(),
        paid_at = now(),
        updated_at = now()
    where id = v_request.id
    returning * into v_updated;
    v_outcome := 'paid';
  else
    update public.payment_requests
    set expense_type = p_expense_type,
        expected_payment_on = p_paid_on,
        paid_on = p_paid_on,
        paid_on_source = 'entered',
        paid_by = auth.uid(),
        paid_at = now(),
        updated_at = now()
    where id = v_request.id
    returning * into v_updated;
    v_outcome := 'legacy_classified';
  end if;

  select array_agg(to_char(month_start, 'YYYY-MM') order by month_start)
  into v_affected_months
  from (
    select distinct date_trunc('month', month_value)::date as month_start
    from unnest(v_lock_months) as affected(month_value)
    where month_value is not null
  ) months;

  insert into public.payment_request_events (
    payment_request_id,
    actor_user_id,
    actor_name,
    event_type,
    from_status,
    to_status,
    metadata
  ) values (
    v_updated.id,
    v_actor_id,
    v_actor_name,
    p_action,
    v_request.status,
    v_updated.status,
    jsonb_build_object(
      'action', p_action,
      'amount', v_updated.amount,
      'from_status', v_request.status,
      'to_status', v_updated.status,
      'old_expense_type', v_request.expense_type,
      'new_expense_type', v_updated.expense_type,
      'old_expected_payment_on', v_request.expected_payment_on,
      'new_expected_payment_on', v_updated.expected_payment_on,
      'old_paid_on', v_request.paid_on,
      'new_paid_on', v_updated.paid_on,
      'approval_reason', v_updated.approval_reason
    )
  );

  foreach v_month_key in array v_affected_months loop
    v_summaries := v_summaries || jsonb_build_array(
      jsonb_build_object(
        'month', v_month_key,
        'summary', public.payment_request_month_summary((v_month_key || '-01')::date)
      )
    );
  end loop;

  return jsonb_build_object(
    'request', public.payment_request_api_record(v_updated.id),
    'affectedMonths', coalesce(to_jsonb(v_affected_months), '[]'::jsonb),
    'summaries', v_summaries,
    'outcome', v_outcome
  );
end;
$$;

-- Remove the legacy transparent browser policies and close direct table access.
drop policy if exists payment_requests_select_all on public.payment_requests;
drop policy if exists payment_requests_insert_own on public.payment_requests;
drop policy if exists payment_requests_update_all on public.payment_requests;

alter table public.payment_requests enable row level security;
alter table public.payment_requests force row level security;
alter table public.payment_request_events enable row level security;
alter table public.payment_request_events force row level security;
alter table public.payment_request_managers enable row level security;
alter table public.payment_request_managers force row level security;

revoke all on public.payment_requests from public;
revoke all on public.payment_requests from anon;
revoke all on public.payment_requests from authenticated;
grant all on public.payment_requests to service_role;
grant all on public.payment_requests to postgres;

revoke all on public.payment_request_events from public;
revoke all on public.payment_request_events from anon;
revoke all on public.payment_request_events from authenticated;
grant all on public.payment_request_events to service_role;
grant all on public.payment_request_events to postgres;

revoke all on table public.payment_request_managers from public;
revoke all on table public.payment_request_managers from anon;
revoke all on table public.payment_request_managers from authenticated;
grant all on table public.payment_request_managers to service_role;
grant all on table public.payment_request_managers to postgres;

do $$
begin
  if exists (select 1 from pg_roles where rolname = 'readonly') then
    execute 'revoke all on table public.payment_request_managers from readonly';
    execute 'revoke all on public.payment_request_events from readonly';
    execute 'revoke all on table public.payment_requests from readonly';
    execute 'grant select (id, user_id, department, description, amount, project_id, comment, status, decided_by, decided_at, decision_comment, created_at, expense_type, expected_payment_on, urgency, approval_reason, paid_on, paid_on_source, paid_by, paid_at, updated_at) on table public.payment_requests to readonly';
  end if;
end;
$$;

revoke all on function public.can_use_payment_requests() from public;
revoke all on function public.can_use_payment_requests() from anon;
revoke all on function public.can_use_payment_requests() from authenticated;
grant execute on function public.can_use_payment_requests() to authenticated;

revoke all on function public.can_manage_payment_requests() from public;
revoke all on function public.can_manage_payment_requests() from anon;
revoke all on function public.can_manage_payment_requests() from authenticated;
grant execute on function public.can_manage_payment_requests() to authenticated;

revoke all on function public.payment_request_month_limit(date) from public;
revoke all on function public.payment_request_month_limit(date) from anon;
revoke all on function public.payment_request_month_limit(date) from authenticated;

revoke all on function public.lock_payment_request_months(date[]) from public;
revoke all on function public.lock_payment_request_months(date[]) from anon;
revoke all on function public.lock_payment_request_months(date[]) from authenticated;

revoke all on function public.lock_payment_request_submission(uuid, uuid) from public;
revoke all on function public.lock_payment_request_submission(uuid, uuid) from anon;
revoke all on function public.lock_payment_request_submission(uuid, uuid) from authenticated;

revoke all on function public.payment_request_api_record(uuid) from public;
revoke all on function public.payment_request_api_record(uuid) from anon;
revoke all on function public.payment_request_api_record(uuid) from authenticated;

revoke all on function public.list_payment_requests(date) from public;
revoke all on function public.list_payment_requests(date) from anon;
revoke all on function public.list_payment_requests(date) from authenticated;
grant execute on function public.list_payment_requests(date) to authenticated;

revoke all on function public.payment_request_month_summary(date) from public;
revoke all on function public.payment_request_month_summary(date) from anon;
revoke all on function public.payment_request_month_summary(date) from authenticated;
grant execute on function public.payment_request_month_summary(date) to authenticated;

revoke all on function public.submit_payment_request(uuid, text, text, numeric, uuid, text, text, date, text, text) from public;
revoke all on function public.submit_payment_request(uuid, text, text, numeric, uuid, text, text, date, text, text) from anon;
revoke all on function public.submit_payment_request(uuid, text, text, numeric, uuid, text, text, date, text, text) from authenticated;
grant execute on function public.submit_payment_request(uuid, text, text, numeric, uuid, text, text, date, text, text) to authenticated;

revoke all on function public.transition_payment_request(uuid, text, timestamptz, text, date, text) from public;
revoke all on function public.transition_payment_request(uuid, text, timestamptz, text, date, text) from anon;
revoke all on function public.transition_payment_request(uuid, text, timestamptz, text, date, text) from authenticated;
grant execute on function public.transition_payment_request(uuid, text, timestamptz, text, date, text) to authenticated;

comment on table public.payment_request_managers is
  'Sealed capability table for the sole payment request decision maker.';
comment on table public.payment_request_events is
  'Append-only audit trail for payment request lifecycle changes.';
comment on column public.payment_requests.document_url is
  'Private supporting document URL; exposed only to the requester and payment manager.';
