-- LinkedIn Outreach 2.0: drop dead `booking_link` column from li2_campaigns.
--
-- The column was added in the original v2 scaffold (migration
-- 20260520_0002_create_li_outreach_v2.sql) on the assumption the AI agent
-- would drop a calendar booking link into LinkedIn conversations. In practice
-- the link was never wired into the OpenOutreach `start` job payload
-- (campaigns/[id]/start/route.ts never reads it), so the runtime never saw
-- it — UI collected data → DB column → dead end.
--
-- Removing the column instead of wiring it through because the v2 booking
-- flow isn't planned (per product). The UI input and POST/PATCH allow-list
-- entries were stripped in the same commit; this just cleans the DB.
alter table public.li2_campaigns drop column if exists booking_link;
