# Generated by Django 6.0.3 on 2026-03-17 18:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("linkedin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("last_name", models.CharField(blank=True, default="", max_length=100)),
                (
                    "company_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("linkedin_url", models.URLField(blank=True, default="", unique=True)),
                (
                    "public_identifier",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("embedding", models.BinaryField(blank=True, null=True)),
                ("disqualified", models.BooleanField(default=False)),
                (
                    "creation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("update_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
            },
        ),
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Qualified", "Qualified"),
                            ("Ready to Connect", "Ready To Connect"),
                            ("Pending", "Pending"),
                            ("Connected", "Connected"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                        ],
                        default="Qualified",
                        max_length=20,
                    ),
                ),
                (
                    "closing_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                            ("Disqualified", "Disqualified"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("connect_attempts", models.IntegerField(default=0)),
                ("backoff_hours", models.IntegerField(default=0)),
                (
                    "creation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("update_date", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deals",
                        to="linkedin.campaign",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crm.lead"
                    ),
                ),
            ],
            options={
                "verbose_name": "Deal",
                "verbose_name_plural": "Deals",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("lead", "campaign"), name="unique_deal_per_campaign"
                    )
                ],
            },
        ),
    ]
