# Generated by Django 6.0.3 on 2026-04-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_lead_urn'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='chat_summary',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='profile_summary',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
