# Generated by Django 6.0.3 on 2026-04-11 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_deal_summaries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='profile_data',
        ),
    ]
