# Generated by Django 6.0.3 on 2026-03-23 16:21

from django.db import migrations, models


def delete_old_messages(apps, schema_editor):
    """Delete pre-sync ChatMessages that have no linkedin_urn."""
    ChatMessage = apps.get_model("chat", "ChatMessage")
    ChatMessage.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(delete_old_messages, migrations.RunPython.noop),
        migrations.AddField(
            model_name="chatmessage",
            name="is_outgoing",
            field=models.BooleanField(
                default=True,
                help_text="True if sent by us, False if received",
                verbose_name="Outgoing",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="linkedin_urn",
            field=models.CharField(
                help_text="entityUrn from Voyager API, used for dedup",
                max_length=300,
                unique=True,
                verbose_name="LinkedIn message URN",
            ),
        ),
    ]
